# Generated by Django 4.0.2 on 2022-02-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0002_remove_game_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status_code',
            field=models.IntegerField(default=-999),
            preserve_default=False,
        ),
    ]
