# Generated by Django 4.0.2 on 2022-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0004_game_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(default=-999, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
