# Generated by Django 4.0.2 on 2022-02-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0005_remove_game_id_game_game_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
