# Generated by Django 4.0.2 on 2022-02-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0007_hiddengamepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddengamepreferences',
            name='min_score_difference',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hiddengamepreferences',
            name='minutes_remaining',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='hiddengamepreferences',
            name='hide_after_period',
            field=models.IntegerField(default=4),
        ),
    ]
