# Generated by Django 4.0.2 on 2022-02-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0008_hiddengamepreferences_min_score_difference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiddengamepreferences',
            old_name='min_score_difference',
            new_name='max_score_difference',
        ),
    ]
