# Generated by Django 4.0.2 on 2022-02-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0009_rename_min_score_difference_hiddengamepreferences_max_score_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddengamepreferences',
            name='hide_scores',
            field=models.BooleanField(default=False),
        ),
    ]
